services:
  frontend:
    build:
      context: ./frontend
    # No ports needed

  backend:
    build:
      context: ./backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/secure-nest

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: