services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount from root
      - ./frontend/dist:/usr/share/nginx/html:ro        # Frontend build output
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend  # Builds using frontend/Dockerfile
    # No ports or volumes needed (handled by Nginx)

  backend:
    build:
      context: ./backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/secure-nest
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: