version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro  # Match your build output
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
    # No ports needed - served via nginx

  backend:
    build:
      context: ./backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/secure-nest
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: