pipeline {
    agent any

    stages {
        stage('Clean Workspace') {
            steps {
                sh '''
                    # Ensure the target directory exists
                    mkdir -p /var/lib/jenkins/DevOps

                    # Remove everything inside the directory
                    rm -rf /var/lib/jenkins/DevOps/*

                    echo "Cleaned /var/lib/jenkins/DevOps/"
                '''
            }
        }

        stage('Fetch Code') {
            steps {
                sh 'git clone https://github.com/arrehman3/WebLabMid.git /var/lib/jenkins/DevOps/'
            }
        }

        stage('Build and Start Docker Compose') {
            steps {
                dir('/var/lib/jenkins/DevOps') {
                    sh 'docker compose up -d'
                }
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed!'
        }
        success {
            echo 'Pipeline succeeded!'
        }
    }
}