pipeline {
    agent any

    stages {
        stage('Clean Workspace') {
            steps {
                sh '''
                    # Make sure the base DevOps folder exists
                    mkdir -p /var/lib/jenkins/DevOps

                    # Clean the subdirectory where we'll clone the repo
                    rm -rf /var/lib/jenkins/DevOps/web-mid

                    echo "Cleaned /var/lib/jenkins/DevOps/web-mid/"
                '''
            }
        }

        stage('Fetch Code') {
            steps {
                sh 'git clone https://github.com/arrehman3/WebLabMid.git /var/lib/jenkins/DevOps/web-mid'
            }
        }

        stage('Build and Start Backend') {
            steps {
                dir('/var/lib/jenkins/DevOps/web-mid/backend') {
                    sh '''
                        docker build -t web-mid-backend .
                        docker compose up -d
                    '''
                }
            }
        }

        stage('Build and Start Frontend') {
            steps {
                dir('/var/lib/jenkins/DevOps/web-mid/frontend') {
                    sh '''
                        docker build -t web-mid-frontend .
                        docker compose up -d
                    '''
                }
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed!'
        }
        success {
            echo 'Pipeline succeeded!'
        }
    }
}
